apiVersion: v1
kind: Service
metadata:
  name: budget-mathapi-service
  namespace: dev
spec:
  selector:
    app: budget-mathapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP 