apiVersion: v1
kind: ConfigMap
metadata:
  name: budget-mathapi-dev-config
  namespace: dev
data:
  PYTHONPATH: "/app"
  FLASK_APP: "app/app.py"
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  API_SERVICE_URL: "http://budget-api-service:4000"
  CORS_ORIGINS: "https://budget-dev.vandenit.be" 