name: Deploy to Digital Ocean Kubernetes

on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker web image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/web/Dockerfile
          push: true
          tags: filipvdb321/budget-web:${{ github.sha }}

      - name: Build and push Docker api image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/api/Dockerfile
          push: true
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          tags: filipvdb321/budget-api:${{ github.sha }}

      - name: Build and push Docker mathapi image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/mathapi/Dockerfile
          push: true
          tags: filipvdb321/budget-mathapi:${{ github.sha }}
          cache-from: type=registry,ref=filipvdb321/budget-mathapi:buildcache
          cache-to: type=registry,ref=filipvdb321/budget-mathapi:buildcache,mode=max

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Replace image tag in web Kubernetes deployment file
        run: |
          envsubst '$IMAGE_TAG' < ./kube/dev/web-deployment.yml.template > ./kube/dev/web-deployment.yml

      - name: Replace image tag in api Kubernetes deployment file
        run: |
          envsubst '$IMAGE_TAG' < ./kube/dev/api-deployment.yml.template > ./kube/dev/api-deployment.yml

      - name: Replace image tag in mathapi Kubernetes deployment file
        run: |
          envsubst '$IMAGE_TAG' < ./kube/dev/mathapi-deployment.yml.template > ./kube/dev/mathapi-deployment.yml

      - name: Save Digital Ocean kubeconfig
        run: doctl kubernetes cluster kubeconfig save k8s-1-vandenit-ams3-dev

      - name: Deploy all config to Kubernetes
        run: |
          kubectl apply -f ./kube/config/dev

      - name: Deploy web config to Kubernetes
        run: |
          kubectl apply -f ./kube/dev/web-deployment.yml

      - name: Deploy api config to Kubernetes
        run: |
          kubectl apply -f ./kube/dev/api-deployment.yml

      - name: Deploy mathapi config to Kubernetes
        run: |
          kubectl apply -f ./kube/dev/mathapi-deployment.yml

      - name: Deploy web service to Kubernetes
        run: |
          kubectl apply -f ./kube/dev/web-service.yml
      - name: Deploy api service to Kubernetes
        run: |
          kubectl apply -f ./kube/dev/api-service.yml
      - name: Deploy mathapi service to Kubernetes
        run: |
          kubectl apply -f ./kube/dev/mathapi-service.yml

      - name: Verify web deployment
        run: kubectl rollout status deployment/budget-web-app -n dev

      - name: Verify api deployment
        run: kubectl rollout status deployment/budget-api-app -n dev

      - name: Verify mathapi deployment
        run: kubectl rollout status deployment/budget-mathapi-app -n dev
