name: Deploy to Digital Ocean Kubernetes

on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies and run tests
        run: |
          cd packages/mathapi
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Run only unit tests in CI - integration tests require real DB/API connections
          python -m pytest app/tests/unit/ -v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.actor != 'dependabot[bot]'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker web image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/web/Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: filipvdb321/budget-web:${{ github.sha }}
          cache-from: type=registry,ref=filipvdb321/budget-web:buildcache
          cache-to: type=registry,ref=filipvdb321/budget-web:buildcache,mode=max

      - name: Build Docker api image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/api/Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          secrets: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          tags: filipvdb321/budget-api:${{ github.sha }}
          cache-from: type=registry,ref=filipvdb321/budget-api:buildcache
          cache-to: type=registry,ref=filipvdb321/budget-api:buildcache,mode=max

      - name: Build Docker mathapi image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./packages/mathapi/Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: filipvdb321/budget-mathapi:${{ github.sha }}
          cache-from: type=registry,ref=filipvdb321/budget-mathapi:buildcache
          cache-to: type=registry,ref=filipvdb321/budget-mathapi:buildcache,mode=max

      - name: Install doctl
        if: github.actor != 'dependabot[bot]'
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Replace image tag in web Kubernetes deployment file
        if: github.actor != 'dependabot[bot]'
        run: |
          envsubst '$IMAGE_TAG' < ./kube/dev/web-deployment.yml.template > ./kube/dev/web-deployment.yml

      - name: Replace image tag in api Kubernetes deployment file
        if: github.actor != 'dependabot[bot]'
        run: |
          envsubst '$IMAGE_TAG' < ./kube/dev/api-deployment.yml.template > ./kube/dev/api-deployment.yml

      - name: Replace image tag in mathapi Kubernetes deployment file
        if: github.actor != 'dependabot[bot]'
        run: |
          envsubst '$IMAGE_TAG' < ./kube/dev/mathapi-deployment.yml.template > ./kube/dev/mathapi-deployment.yml

      - name: Save Digital Ocean kubeconfig
        if: github.actor != 'dependabot[bot]'
        run: doctl kubernetes cluster kubeconfig save k8s-1-vandenit-ams3-dev

      - name: Deploy all config to Kubernetes
        if: github.actor != 'dependabot[bot]'
        run: |
          kubectl apply -f ./kube/config/dev

      - name: Deploy web config to Kubernetes
        if: github.actor != 'dependabot[bot]'
        run: |
          kubectl apply -f ./kube/dev/web-deployment.yml

      - name: Deploy api config to Kubernetes
        if: github.actor != 'dependabot[bot]'
        run: |
          kubectl apply -f ./kube/dev/api-deployment.yml

      - name: Deploy mathapi config to Kubernetes
        if: github.actor != 'dependabot[bot]'
        run: |
          kubectl apply -f ./kube/dev/mathapi-deployment.yml

      - name: Deploy web service to Kubernetes
        if: github.actor != 'dependabot[bot]'
        run: |
          kubectl apply -f ./kube/dev/web-service.yml
      - name: Deploy api service to Kubernetes
        if: github.actor != 'dependabot[bot]'
        run: |
          kubectl apply -f ./kube/dev/api-service.yml
      - name: Deploy mathapi service to Kubernetes
        if: github.actor != 'dependabot[bot]'
        run: |
          kubectl apply -f ./kube/dev/mathapi-service.yml

      - name: Verify web deployment
        if: github.actor != 'dependabot[bot]'
        run: kubectl rollout status deployment/budget-web-app -n dev

      - name: Verify api deployment
        if: github.actor != 'dependabot[bot]'
        run: kubectl rollout status deployment/budget-api-app -n dev

      - name: Verify mathapi deployment
        if: github.actor != 'dependabot[bot]'
        run: kubectl rollout status deployment/budget-mathapi-app -n dev
